spring.application.name=orientese

spring.datasource.url=jdbc:oracle:thin:@koxavufkzcf93mf1_low?TNS_ADMIN=./src/main/resources/wallet
spring.datasource.username=ADMIN
spring.datasource.password=Chut&m&#10000
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configurações do Hibernate/JPA para mostrar o SQL no console (ajuda nos estudos)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

api.security.token.secret=Chut&m&#123